spring:
  profiles:
    active: "dev"

---

server:
  port: 8080

spring:
  profiles: dev
  resources:
    static-locations: classpath:/resources/static/**, classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
    continue-on-error: true
    dbcp2:
      driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level: error

---

spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
    continue-on-error: false
    dbcp2:
        driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level: debug